baseURL = "https://band-test.netlify.com"
disableLanguages = []
disqusShortname = "themefisher-template"
googleAnalytics = ""
hasCJKLanguage = false
paginate = "6"
summaryLength = "10"
theme = "airspace-hugo"
timeZone = "UTC"
title = "Seymour Band Test"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "WebAppManifest"]
