[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "FAQ"
url = "faq/"
weight = 6
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "Calendar"
url = ""
weight = "1"
[[main]]
name = "Private Lessons"
url = ""
weight = ""
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "Events"
url = ""
weight = ""
[[main]]
name = "Band Boosters"
url = ""
weight = ""
[[main]]
name = "Blog"
url = "blog/"
weight = 4
[[main]]
name = "FAQ"
parent = "More"
url = "faq/"
weight = 3
[[main]]
name = "Contact"
url = "contact/"
weight = 6
