[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "FAQ"
url = "faq/"
weight = 6
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "Contact"
url = "contact/"
weight = "8"
[[main]]
name = "Merch"
url = ""
weight = ""
[[main]]
name = "About"
url = "about/"
weight = "4"
[[main]]
name = "Events"
url = ""
weight = "5"
[[main]]
name = "Band Boosters"
url = ""
weight = "6"
[[main]]
name = "Private Lessons"
url = ""
weight = "3"
[[main]]
name = "Calendar"
url = ""
weight = "2"
[[main]]
name = "Home"
url = ""
weight = 1
