address_descriptors = false
author = "Themefisher"
copyright = "Seymour High School Band"
custom_script = ""
description = "This is meta description"
email = "zachishi@gmail.com"
favicon = "/images/shsband_logo.jpg"
google_tag_manager = ""
image = "images/logo.png"
location = "Seymour, TN"
logo = "/images/shsband_logo.jpg"
logo_text = "Seymour High School Band"
logo_width = "150px"
navbar_fixed = false
phone = "0124857985320"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = true
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/SeymourBand"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "https://twitter.com/seymourhsbands"
title = "twitter"
[[social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UCgkmfe98z65EWMVvOSv_lzA/featured"
title = "youtube"
